#! /bin/sh


#los atajos de teclado
pgrep -x sxhkd > /dev/null || sxhkd &

# el compton para las trasparencias
#pgrep -x compton> /dev/null || compton --config /home/demon0/.config/compton.conf &

# el picom para las trasparencias
pgrep -x picom > /dev/null || picom --config /home/demon0/.config/picom/picom.conf &


# lanza el polybar
~/.config/polybar/cuts/launch.sh &

# fondo de pantalla
#xfdesktop --disable-wm-check &

# notificaiones con dunst hay que terminar de tunearlo
pgrep -x dunst > /dev/null || dunst -c ~/.config/dunst/dunstrc &

bspc config pointer modifier mod1
bspc config pointer_modifier mod1
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

#bspc config border_radius        10
#bspc config focus_follows_pointer   true


bspc config presel_feedback_color \#00ffb3
bspc config focused_border_color "#00ff95"
#bspc config active_border_color "#03fcea"
bspc config normal_border_color "#ff006a"



bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Qalculate-gtk state=floating

